---
- name: using block statement
  hosts: node1
  become: yes
  tasks:
    - name: Install, configure, and start Apache
      block:
        - name: install httpd
          ansible.builtin.dnf:
            name: httpd
            state: latest

        - name: start & enabled httpd
          ansible.builtin.service:
            name: httpd
            state: started
            enabled: yes

        - name: copy index.html
          ansible.builtin.copy:
            src: files/index.html
            dest: /var/www/html/
      when:
        - exec_block == 'yes'
