---
- name: using galaxy
  hosts: node1
  tasks:
    - ansible.builtin.import_role:
        name: irixjp.role_example_hello

    - ansible.builtin.import_role:
        name: irixjp.role_example_uptime

    - name: get locale
      sample_get_locale:
      register: ret

    - debug: var=ret
