---
- name: add users by loop
  hosts: node1
  become: yes
  vars:
    user_list:
      - apple
      - orange
      - pineapple
      - mango
      - peach
  tasks:
    - name: add a user
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop: "{{ user_list }}"

