---
- hosts: node1
  gather_facts: no
  vars:
    task_vars: 100
  tasks:
    - name: print task_vars 1
      ansible.builtin.debug:
        var: task_vars

    - name: override task_vars
      ansible.builtin.debug:
        var: task_vars
      vars:
        task_vars: 20

    - name: print task_vars 2
      ansible.builtin.debug:
        var: task_vars
