---
- hosts: node1
  gather_facts: no
  vars:
    play_vars:
      - order: 1st word
        value: ansible
      - order: 2nd word
        value: is
      - order: 3rd word
        value: fine
  tasks:
    - name: print play_vars
      ansible.builtin.debug:
        var: play_vars

    - name: access to the array
      ansible.builtin.debug:
        msg: "{{ play_vars[1].order }}"

    - name: join variables
      ansible.builtin.debug:
        msg: "{{ play_vars[0].value}} {{ play_vars[1].value }} {{ play_vars[2].value }}"
