---
- name: start httpd if it's stopped
  hosts: node1
  become: yes
  tasks:
    - name: install httpd
      ansible.builtin.dnf:
        name: httpd
        state: latest

    - name: check httpd processes is running
      ansible.builtin.shell: ps -ef |grep http[d]
      register: ret
      ignore_errors: yes
      changed_when: no

    - name: print return value
      ansible.builtin.debug:
        var: ret

    - name: start httpd (httpd is stopped)
      ansible.builtin.service:
        name: httpd
        state: started
      when:
        - ret.rc == 1
